# Generated by Django 4.2.16 on 2024-11-23 21:12

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0003_ngo'),
    ]

    operations = [
        migrations.RenameField(
            model_name='foodlisting',
            old_name='quantity',
            new_name='total_quantity',
        ),
        migrations.AddField(
            model_name='foodlisting',
            name='restaurant',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='base.restaurant'),
        ),
        migrations.AddField(
            model_name='foodlisting',
            name='status',
            field=models.CharField(default='available', max_length=20),
        ),
        migrations.CreateModel(
            name='FoodClaim',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('claimed_quantity', models.PositiveIntegerField()),
                ('food_listing', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='base.foodlisting')),
                ('ngo', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='base.ngo')),
            ],
        ),
        migrations.AddField(
            model_name='foodlisting',
            name='claimed_by',
            field=models.ManyToManyField(related_name='claimed_food', through='base.FoodClaim', to='base.ngo'),
        ),
    ]
