# Generated by Django 4.2.16 on 2024-11-26 18:23

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0005_ngo_user_restaurant_user'),
    ]

    operations = [
        migrations.AlterField(
            model_name='foodlisting',
            name='restaurant',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='food_listings', to='base.restaurant'),
        ),
    ]
