# Generated by Django 4.2.16 on 2024-11-27 03:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0007_alter_restaurant_email'),
    ]

    operations = [
        migrations.AddField(
            model_name='foodclaim',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
    ]
