# Generated by Django 4.2.16 on 2024-11-27 03:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0008_foodclaim_created_at'),
    ]

    operations = [
        migrations.RenameField(
            model_name='foodclaim',
            old_name='created_at',
            new_name='claimed_at',
        ),
    ]
